import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";

import { authOptions } from "@/lib/auth";
import { requireSubscription } from "@/lib/access";
import { prisma } from "@/lib/prisma";
import { runCalculationEngine, CalculationInput } from "@/lib/calculator";

function isFiniteNumber(value: unknown) {
  return typeof value === "number" && Number.isFinite(value);
}

function normalizeScenarioName(value: unknown) {
  if (typeof value !== "string") {
    return "Live Scenario";
  }

  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed.slice(0, 80) : "Live Scenario";
}

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const user = await prisma.user.findUnique({
      where: { id: session.user.id },
      select: {
        id: true,
        accessType: true,
        subscriptionStatus: true,
      },
    });

    if (!user || !requireSubscription(user as any)) {
      return NextResponse.json({ error: "Subscription required to save scenarios" }, { status: 403 });
    }

    const body: Record<string, unknown> = await req.json();

    const input: CalculationInput = {
      incomeOwn: Number(body.incomeOwn),
      incomeSpouse: Number(body.incomeSpouse),
      childrenCount: Number(body.childrenCount),
      expenses: Number(body.expenses),
      custodyPercentage: Number(body.custodyPercentage),
      mortgage: Number(body.mortgage) || 0,
      childcare: Number(body.childcare) || 0,
      school: Number(body.school) || 0,
      activities: Number(body.activities) || 0,
      utilities: Number(body.utilities) || 0,
      insurance: Number(body.insurance) || 0,
      otherExpenses: Number(body.otherExpenses) || 0,
      savings: Number(body.savings) || 0,
      retirement: Number(body.retirement) || 0,
      homeEquity: Number(body.homeEquity) || 0,
      assetSplit: body.assetSplit as any,
      retirementImpact: body.retirementImpact as any,
      vaDisability: body.vaDisability as any,
      housingScenario: body.housingScenario as any,
    };

    const results = runCalculationEngine(input);
    const scenarioName = normalizeScenarioName(body.name);

    const scenario = await prisma.scenario.create({
      data: {
        userId: user.id,
        name: scenarioName,
        userIncome: input.incomeOwn,
        spouseIncome: input.incomeSpouse,
        childrenCount: Math.trunc(input.childrenCount),
        custodyPercent: input.custodyPercentage,
        mortgage: input.mortgage ?? 0,
        childcare: input.childcare ?? 0,
        school: input.school ?? 0,
        activities: input.activities ?? 0,
        utilities: input.utilities ?? 0,
        insurance: input.insurance ?? 0,
        otherExpenses: input.otherExpenses ?? 0,
        savings: input.savings,
        retirement: input.retirement,
        homeEquity: input.homeEquity,
        assetSplit: input.assetSplit,
        retirementImpact: input.retirementImpact,
        vaDisability: input.vaDisability,
        housingScenario: input.housingScenario,
        netIncome: results.netMonthlyIncome,
        monthlySupport: results.monthlySupport,
        totalExpenses: results.totalMonthlyExpenses,
        disposableIncome: results.disposableIncome,
        realityScore: results.impactPercentage * 100,
        realityLevel: results.realityScoreStatus.toLowerCase(),
        isAutoGenerated: false,
      },
    });

    return NextResponse.json({
      success: true,
      data: scenario,
    });
  } catch (error) {
    console.error("Scenario Save Error:", error);
    return NextResponse.json({ error: "Failed to save scenario" }, { status: 500 });
  }
}